-intstyle "ise" -incremental -o "C:/Users/user/HSCD/Uebung/Aufgabe3/xwork/A3/insertcore_tb_isim_beh.exe" -prj "C:/Users/user/HSCD/Uebung/Aufgabe3/xwork/A3/insertcore_tb_beh.prj" "work.insertcore_tb" 
